name = "jiwonz/task"
version = "0.2.0-rc.2"
description = "Get the task library for Roblox or Lune or Luau"
authors = ["jiwonz <me@jiwonz.kr>", "jackdotink"]
repository = "https://github.com/jiwonz/luau-task"
license = "MIT"
private = true
includes = ["src/**", "pesde.toml", "LICENSE", "README.md"]

[target]
environment = "lune"
lib = "src/lib/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
lune = "^0.8.9"
pesde = "^0.6.0"

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.3.7" }
multitarget = { name = "jiwonz/multitarget", version = "^0.4.0-rc.27" }
darklua = { name = "pesde/darklua", version = "^0.16.0" }
