name = "jiwonz/task"
version = "0.1.0"
description = "Get the task library for Roblox or Lune or Luau"
authors = ["jiwonz <me@jiwonz.kr>", "jackdotink"]
repository = "https://github.com/jiwonz/luau-task"
license = "MIT"
private = true
includes = ["src/**", "pesde.toml", "LICENSE", "README.md"]

[target]
environment = "luau"
lib = "src/lib/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
build = "scripts/build.luau"

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.3.7", target = "lune" }
multitarget = { name = "jiwonz/multitarget", version = "^0.2.2", target = "lune" }
darklua = { name = "pesde/darklua", version = "^0.16.0", target = "lune" }
